on:    
  push:
    branches:
    - 'main'

jobs:
  Publish:
    runs-on: ubuntu-latest
    steps:
 
        - uses: aammirmirza/Publish2PSGallery@PSGallery_v2
          with:          
            NuGetApiKey: $(NuGetApiKey)        
            modulePath: './'
